### ISSUE TITLE
Error using BDV-compatible hdf5 fusion in BigStitcher

### ISSUE THREAD

**Issue by ScientistRachel** [PreibischLab/multiview-reconstruction#37] opened 2023-02-14 16:03 UTC
We would like to use BigStitcher to fuse two angles acquired on a SiMView microscope into a BDV-compatible hdf5 file (e.g., to use with Mastodon tracking).  However, when I try to use the Advanced Fusion menu to complete this export, I reproducibly end up with an error message after it finishes fusing the 0th timepoint:
 
Exception in thread "Thread-247" java.lang.UnsupportedOperationException
                at java.util.Collections$UnmodifiableCollection.add(Collections.java:1057)
                at net.preibisch.mvrecon.process.export.ExportTools.writeSpimData(ExportTools.java:231)
                at net.preibisch.mvrecon.process.export.ExportTools.writeBDVMetaData(ExportTools.java:142)
                at net.preibisch.mvrecon.process.export.ExportN5API.exportImage(ExportN5API.java:252)
                at net.preibisch.mvrecon.fiji.plugin.Image_Fusion.fuse(Image_Fusion.java:280)
                at net.preibisch.mvrecon.fiji.spimdata.explorer.popup.FusionPopup$MyActionListener$1.run(FusionPopup.java:82)
                at java.lang.Thread.run(Thread.java:750)
 
I’ve tried downloading a fresh version of FIJI and updating to the latest BigStitcher to hopefully avoid any version issues, and I’ve also had the problem with two different datasets. I will attach the Console and Log from a failed fusion attempt on a mini dataset of 6 timepoints.  Thank you for any suggestions!

[Console_ErrorMessage.txt](https://github.com/PreibischLab/multiview-reconstruction/files/10734392/Console_ErrorMessage.txt)
[Log_FailedOnTimepoint1.txt](https://github.com/PreibischLab/multiview-reconstruction/files/10734393/Log_FailedOnTimepoint1.txt)

**Comment by mzouink** [comment] 2023-02-14 19:16
@ScientistRachel The bug should be fixed by now. can you please update Fiji and try it

**Comment by ScientistRachel** [comment] 2023-02-16 18:41
@mzouink I tried the new version, but unfortunately when I try to save more than one timepoint FIJI just crashes.  I don't get an error message on the Log or Console before the entire program just shuts itself down.  I will attach the log as it looks right before the crash.  T = 0, Channel 1 fuses successfully, then T = 0, Channel 2 fuses succesfully, and then T = 1, Channel 1 starts.  T=1, Channel 1 then crashes about at the timepoint I would have expected it to finish, based on the other two fusions (~13:15 to compare to the attached log).

[Log_LastUpdateBeforeCrash.txt](https://github.com/PreibischLab/multiview-reconstruction/files/10759317/Log_LastUpdateBeforeCrash.txt)

**Comment by StephanPreibisch** [comment] 2023-02-16 18:49
Hi @ScientistRachel, could you please check if it works when fusing a) TIFF images or b) non-BDV HDF5?

And for the bug, could you run Fiji from the command line to see the error message? It is definitely very a weird behavior that Java itself shuts down ... would love to be able to re-produce it.

**Comment by StephanPreibisch** [comment] 2023-02-16 19:11
@ScientistRachel , I just fused a 2-timepoint dataset as BDV-HDF5, and it works fine for me ... so we need to figure out why it crashes on your end ...

**Comment by ScientistRachel** [comment] 2023-02-16 20:17
Hi Stephan, I checked and it works correctly if fusing to TIFF images or a non-BDV HDF5.  I will attach the output from running in headless mode.  This seems to be the most relevant line: 

ViewId you specified already exists in the XML, cannot continue.

[HeadlessFusionTest.txt](https://github.com/PreibischLab/multiview-reconstruction/files/10760433/HeadlessFusionTest.txt)

**Comment by StephanPreibisch** [comment] 2023-02-16 21:02
I see, there were some System.exit() calls that I removed ... apart from that could it be that you are simply trying to write into a project where the same timepoint already exists?

**Comment by StephanPreibisch** [comment] 2023-02-16 21:05
(which simply means that the XML/H5 exists - because by design you can add new datasets to an existing H5)

**Comment by ScientistRachel** [comment] 2023-02-16 21:14
I am fusing into an empty folder into a new H5 and new XML, so the timepoint shouldn't already exist.

**Comment by StephanPreibisch** [comment] 2023-02-16 21:27
Could you please update Fiji and run it again, it should tell us a little more ... it will tell you which ViewID already exists, we can then check why it is there already ...

**Comment by ScientistRachel** [comment] 2023-02-16 21:28
In the tests that were crashing, I was trying to save timepoints 0 & 1 for both channel 0 & 1.  I just tried saving timepoints 0-2 but only for channel 0 and did not run into any errors.  So, it can save multiple time points when there is one channel.

**Comment by StephanPreibisch** [comment] 2023-02-16 21:29
mmh, that gives me a clue ... I'll try to reproduce

**Comment by StephanPreibisch** [comment] 2023-02-16 21:41
I can reproduce the error, will try to fix it now ...

**Comment by StephanPreibisch** [comment] 2023-02-16 21:49
Should be fixed with commit https://github.com/PreibischLab/multiview-reconstruction/commit/bcbc42f182f924ee8f9af5f361c313e0c952e795

Please update Fiji and it should work @ScientistRachel

**Comment by ScientistRachel** [comment] 2023-02-16 22:11
@StephanPreibisch Channels 0-1 + Timepoints 0-1 fused without any errors.  I also confirmed that I can reopen the fused file and it makes sense visually.  Thank you for your help with this issue!

**Comment by StephanPreibisch** [comment] 2023-02-16 22:26
Thanks for reporting and help us fixing the bugs :)

**Closed by StephanPreibisch** 2023-02-16 22:26 UTC
